[package]
name = "server-project"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }

[[bin]]
name = "server-jk"
path = "src/cmd/tcplistener/main.rs"

